import { Inter } from "next/font/google";
import Theme from "@/utils/Theme";
import "./globals.css";
import { Footer, Navbar } from "@/components";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Oqensea",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme>
          <div className="dark:bg-nft-dark bg-white min-h-screen">
            <Navbar />
            <main className="pt-65">{children}</main>
            <Footer />
          </div>

          <Script
            src="https://kit.fontawesome.com/263f482a1b.js"
            crossorigin="anonymous"
          />
        </Theme>
      </body>
    </html>
  );
}
